---
- name: Ensure systemd service is enabled and started.
  ansible.builtin.systemd:
    name: "{{ vault_service_name }}"
    enabled: true
    state: started

- name: Take time for the service to get fully operator
  ansible.builtin.pause:
    seconds: 120

- name: Check the Vault initialization status.
  ansible.builtin.shell: "{{ vault_binary }} status | grep -i initialized | awk '{print $2}'" # noqa: risky-shell-pipe
  environment:
    VAULT_ADDR: "{{ vault_address }}"
    VAULT_CACERT: "{{ vault_ssl_ca_dest }}"
    VAULT_SKIP_VERIFY: "true"
  changed_when: false
  register: vault_is_initialized
  when: ansible_hostname in groups['vault_servers']
  delegate_to: "{{ groups['vault_servers'] | first }}"
  run_once: true

- name: Initialize the leader Vault.
  ansible.builtin.command: "{{ vault_binary }} operator init"
  environment:
    VAULT_ADDR: "{{ vault_address }}"
    VAULT_CACERT: "{{ vault_ssl_ca_dest }}"
    VAULT_SKIP_VERIFY: "true"
  changed_when: false
  register: vault_init_output
  when:
    - vault_is_initialized.stdout == "false"
  delegate_to: "{{ groups['vault_servers'] | first }}"
  run_once: true

- name: Store Vault master keys local for safekeeping.
  ansible.builtin.copy:
    content: "{{ vault_init_output.stdout }}"
    dest: "{{ vault_bootstrap_init_local_path }}"
    mode: 0644
  become: false
  when:
    - vault_is_initialized.stdout == "false"
  delegate_to: "{{ groups['consul_servers'] | first }}"
  run_once: true

- name: Check if Vault master keys file exists on Consul server
  ansible.builtin.stat:
    path: "{{ vault_bootstrap_init_local_path }}"
  delegate_to: "{{ groups['consul_servers'] | first }}"
  register: vault_master_keys_file
  run_once: true

- name: Print confirmation if Vault master keys file exists
  ansible.builtin.debug:
    msg: "Vault master keys file exists at {{ vault_bootstrap_init_local_path }} on Consul server."
  when: vault_master_keys_file.stat.exists
  run_once: true

- name: Print warning if Vault master keys file does not exist
  ansible.builtin.debug:
    msg: "Vault master keys file does not exist at {{ vault_bootstrap_init_local_path }} on Consul server. Check the initialization and file storage tasks for errors."
  when: not vault_master_keys_file.stat.exists
  run_once: true

