---
galaxy_info:
  author: Greg Bolton
  description: Base Setup for Rocky Linux
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: EL
      versions:
        - 9
  galaxy_tags:
    - linux
    - rocky
    - base

dependencies: []
