locals {
  machine_map = {
    machines = {
      consul1 = {
        name        = "consul1"
        target_node = "cloud"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8000" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.8"
        gateway     = "192.168.50.1"
        description = "test_node"
      },
      consul2 = {
        name        = "consul2"
        target_node = "cloud"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8000" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.9"
        gateway     = "192.168.50.1"
        description = "test_node"
      },
      consul3 = {
        name        = "consul3"
        target_node = "lab"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8001" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.10"
        gateway     = "192.168.50.1"
        description = "test_node"
      },
      vault1 = {
        name        = "vault1"
        target_node = "cloud"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8000" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.11"
        gateway     = "192.168.50.1"
        description = "test_node"
      },
      vault2 = {
        name        = "vault2"
        target_node = "cloud"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8000" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.12"
        gateway     = "192.168.50.1"
        description = "test_node"
      },
      vault3 = {
        name        = "vault3"
        target_node = "lab"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8001" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.13"
        gateway     = "192.168.50.1"
        description = "test_node"
      },
      nomad1 = {
        name        = "nomad1"
        target_node = "cloud"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8000" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.14"
        gateway     = "192.168.50.1"
        description = "test_node"
      },
      nomad2 = {
        name        = "nomad2"
        target_node = "cloud"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8000" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.15"
        gateway     = "192.168.50.1"
        description = "test_node"
      },
      nomad3 = {
        name        = "nomad3"
        target_node = "lab"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8001" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.16"
        gateway     = "192.168.50.1"
        description = "test_node"
      },
      docker1 = {
        name        = "docker1"
        target_node = "lab"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8001" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.17"
        gateway     = "192.168.50.1"
        description = "test_node"
      },
      docker2 = {
        name        = "docker2"
        target_node = "lab"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8001" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.18"
        gateway     = "192.168.50.1"
        description = "test_node"
      },
      docker3 = {
        name        = "docker3"
        target_node = "lab"
        os_type     = "cloud-init"
        agent       = 1        # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone  = true     # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template    = "VM 8001" # Name of Template Used to Clone
        cores       = 2
        socket      = 1
        memory      = 4096
        storage     = "32G"
        ip_address  = "192.168.50.19"
        gateway     = "192.168.50.1"
        description = "test_node"
      }
    }
  }

  sip_machines = lookup(local.machine_map, "machines", {})
}
